---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[monitor::master]
- name: sandbox
  run_list:
    - recipe[haproxy]
    - recipe[graphite]
    - recipe[monitor::master]
    - recipe[monitor::haproxy]
    - recipe[monitor::redis]
    - recipe[monitor::rabbitmq]
  attributes:
    authorization:
      sudo:
        users: ["vagrant", "kitchen"]
        passwordless: true
        include_sudoers_d: true
    haproxy:
      enable_stats_socket: true
    apache:
      listen_ports: [8080]
    graphite:
      listen_port: 8080
      carbon:
        service_type: "init"
    sensu:
      dashboard:
        port: 4000
    monitor:
      metric_handlers: ["graphite"]
      additional_client_attributes:
        haproxy_services: "servers-http"
